//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura
    {
        public int ID_Detalle { get; set; }
        public int DNI_Vendedor { get; set; }
        public int DNI_Cliente { get; set; }
        public string Modelo { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int ID_Factura { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
